
name: Build and Test and Deploiment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration_tests:

    runs-on: ubuntu-latest
 

    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Npm Install
      run: npm install
    - name: Run tests
      run: npm test


  deploy_render:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: integration_tests

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          

